# Generated by Django 5.0.6 on 2024-07-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
